#################
### AUTOSTART ###
#################
exec-once = ags
exec-once = hyprshade auto
exec-once = hypridle
exec-once = nm-applet
exec-once = syncthing --no-browser
exec-once = waybar
exec-once = waypaper --restore
