###################
### WINDOW RULES ##
###################
# https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule = opacity 1.0 override, class:firefox
windowrule = opacity 1.0 override, class:vlc
windowrule = opacity 1.0 override, initialTitle:qView

windowrule = float, title:(File Operation Progress) # file transfer window
windowrule = float, title:(Rename )(.*") # renaming window
windowrule = float, class:blueman-manager
windowrule = float, class:nm-connection-editor
windowrule = float, class:nwg-displays
windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = float, class:vlc

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
