###################
### WINDOW RULES ##
###################
# https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule = opacity 1.0 override, class:firefox
windowrule = opacity 1.0 override, class:vlc
windowrule = opacity 1.0 override, initialTitle:qView

windowrule = float, title:(File Operation Progress)
windowrule = float, title:(Bluetooth Devices)

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
